name: next_dart_server
description: Authoring DSL and HTTP endpoints for next-dart backends.
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.12.0
dependencies:
  next_dart_protocol:
    path: ../next_dart_protocol
  cryptography: ^2.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
dev_dependencies:
  test: ^1.31.1
