// examples/counter_app/server/lib/keys.dart
// Generated by tool/gen_keys.dart — keep identical values in app/lib/keys.dart.
const signingSeedB64 = '4QuA0ubJNeYefQbjsv57QYQ/usU1K7fk/4zv/lRlfbg=';
const signingPublicKeyB64 = 'DQgjF99pkNXN/Xnym4R+xLOiAxPjsRG7NbJnkTVe1xQ=';
const secretKeyB64 = 'DRQbIikwNz5FTFNaYWhvdn2Ei5KZoKeutbzDytHY3+Y=';
