// examples/counter_app/server/lib/keys.dart
// Generated by tool/gen_keys.dart — keep identical values in app/lib/keys.dart.

// ════════════════════════════════════════════════════════════════════
// DEMO KEYS — NOT FOR PRODUCTION USE.
// These values are committed to a public repository, so anyone can read
// them. They exist only so the example runs out of the box. Before
// deploying anything real, run `dart run tool/gen_keys.dart` to generate
// fresh random keys and keep secrets out of version control.
// ════════════════════════════════════════════════════════════════════
const signingSeedB64 = '4QuA0ubJNeYefQbjsv57QYQ/usU1K7fk/4zv/lRlfbg=';
const signingPublicKeyB64 = 'DQgjF99pkNXN/Xnym4R+xLOiAxPjsRG7NbJnkTVe1xQ=';
const secretKeyB64 = 'DRQbIikwNz5FTFNaYWhvdn2Ei5KZoKeutbzDytHY3+Y=';
